### ISSUE TITLE
Where did ggaverage go?

### ISSUE THREAD

**Issue by dustingilbreath** [strengejacke/ggeffects#100]
The title says it all. I love the package overall, and used ggaverage quite a bit, but I'm getting an error message saying its missing. As far as I understand it, ggaverage was calculating the marginal effects from the predicted value through averaging the predicted values in each group within the category of a factor. ggemmeans appears to hold the factor constant to the base category of the factor or another specified category. For many survey contexts, this leads to problematic predicted values. 

Is ggaverage going to return or is it gone?

**Comment by dustingilbreath** [comment]
Figured out a work around to the problem. Thanks for the package!

**Comment by strengejacke** [comment]
ggaverage did some really crude averaging, which is not really precise for models with non-Gaussian family. Therefore, because results were not really reliable and probably misleading, I decided to remove that function from the package.

**Comment by dustingilbreath** [comment]
That's interesting. What I was getting was doing much better when there were factor variables than with ggeffect and ggpredict.

**Comment by tomBSUC** [comment]
To confirm, have ggaverage been intentionally removed from most recent versions of ggeffects, including the latest version?  I ask because this page still refers to it, and the page’s date is today:  [Technical Details: Difference between ggpredict(), ggemmeans() and ggaverage()](https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html#:~:text=For%20categorical%20predictors%2C%20ggpredict(),of%20the%20categories%20of%20factors.)

Perhaps you could clarify on that page that ggaverage is not available for <INSERT list of versions such that it is not available>. Would be helpful for folks who are not a familiar with how to figure this out on their own.

Thank you for clarifying, 
Tom

**Comment by strengejacke** [comment]
It's added back in the current development version and will be available in the next update. There's now a more reliable way to calculate average predictions.

**Comment by tomBSUC** [comment]
Great, but just to clarify for a GitHub novice, by the "current development version", do you mean the [version of ggaverage currently in this GitHub directory](https://github.com/strengejacke/ggeffects/blob/master/R/ggaverage.R)?  That version uses marginaleffects::avg_predictions . Is avg_predictions more reliable than what the old (deprecated) ggaverage used to use?  Thank you for clarifying, Tom

**Comment by strengejacke** [comment]
Yes, you can easily install the dev version via r-universe, see
https://strengejacke.github.io/ggeffects/#installation

> Is avg_predictions more reliable than what the old (deprecated) ggaverage used to use?

Yes, in particular for non Gaussian models, and the standard errors and confidence intervals are more accurate.
