### ISSUE TITLE
Differences between ggeffect and ggpredict

### ISSUE THREAD

**Issue by kikollan** [strengejacke/ggeffects#16]
The package is really useful. I have been using `Effects` for a while, and having it tidy is great.

May I ask about the differences between `ggeffect`, `ggpredict` and `ggaverage`? I am having problems understanding the differences between the first and the other two. Adding `ggeffect` to the Vignette might be very useful. For instance, I have been trying to replicate the results provided by `effects:Effect` using `predict` with no success.

**Comment by strengejacke** [comment]
First, the difference between `ggpredict()` and `ggeffect()`. There are some information in the _Details_ section of `?ggpredict` as well.

`ggpredict()` uses the predict function. I create a unique combination of all possible values from the data (model frame) with `expand.grid` for those terms specified in `terms`. This is the same as for `ggeffect()`. However, predictors that should be hold constant, are handled differently. For both `ggpredict()` and `ggeffect()`, continuous values are held constant at their mean value (unless changed by the `typical`-argument). However, since the `predict()`-function used in `ggpredict()` needs valid factor levels, categorical variables are set to their reference level. `ggeffect()`, however, which wraps `effects::Effect()`, uses the _proportion_ for categorial variables. Say, you have 30% men (coded as 0) and 70% women (coded as 1), this factor would
be held constant at 0.7 (and not 0, the reference level). You can't do this with `predict()`, as `predict()` requires valid factor levels for the `newdata`.

`ggaverage()` computes the average predicted values, by calling `ggpredict()` with `full.data = TRUE`, where argument `newdata = model.frame(model)` is used in `predict()`. Hence, predictions are made on the model data. In this case, _all remaining covariates_ that are not specified in terms are _not_ held constant, but vary between observations (and are kept as they happen to be). The predicted values are then averaged for each group (if any).

Does this help?

**Comment by kikollan** [comment]
@strengejacke, thanks! It is now clear to me. Sorry I miss the note in `?ggpredict`.

Following Stata conventions ([R Williams](https://www3.nd.edu/~rwilliam/stats/Margins01.pdf)), there are three types of predictions/marginal effects. They can be computed with `ggeffects` as follows:

`ggpredict()` - **Adjusted Predictions at the Means** (using reference levels to fix factors)
`ggeffects()` - **Adjusted Predictions at the Means** (using proportions to fix factors)
 (This second case is not easy to replicate with `predict`)

`ggaverage()` - **Average Adjusted Predictions** (averaged prediction made on the mode data)

The last case in Stata is **Adjusted Predictions at Representative values** (MERs). Those (basically, predictions at given values/levels) can be computed those using something like `ggpredict(fit, terms = c("c12hour [30, 50, 80]", "c172code [1,3]"))`, with the limitation of only fixing three covariates. Or we can use `predict`, directly. A tidy wrap may be useful, but `modelr` works fine there.

Thanks again.

**Comment by strengejacke** [comment]
> Those (basically, predictions at given values/levels) can be computed those using something like ggpredict(fit, terms = c("c12hour [30, 50, 80]", "c172code [1,3]")), with the limitation of only fixing three covariates. Or we can use predict, directly. A tidy wrap may be useful, but modelr works fine there.

I'm not sure, but if you think of setting a given value for _each_ model-predictor, you end up having just a single value, which is not feasible for graphical output. Maybe, if you're just interested in the number(s), you may take a look at the *margins* package from Thomas Leeper.

**Comment by kikollan** [comment]
Right. I mean setting a given value for each model-predictor, but one. The idea es representing the effect of that particular predictor when all the other are at given "representative values" instead of fixing them "at means". This can be done with two or three "free" predictors, and plotting using color/facet, as you suggest. 

The idea, basically, is allowing the user to fix predictors at "representative values" instead of fixing them (automatically) at "mean values", as `ggpredict` and `ggeffects` do. Is the simpler, more manual case, and wrapping `Effects` or `predicts` might work. See, for example, `given.values` at `Effects`. If representative values are not given for all predictors, the rest could be fixed at means as default in `ggpredict` and `ggeffects`.

**Comment by strengejacke** [comment]
You can pass further arguments down to `effects::Effect()` via `ggeffect()`, maybe you can use `given.values` in this way?
