### ISSUE TITLE
maintain variable names in data frame

### ISSUE THREAD

**Issue by schmettow** [strengejacke/ggeffects#18]
first of all: thank you so much for this work! I've been searching for something like this for years. I will most likely introduce ggeffects in the book I am writing.

Still, I am wondering, why in the produced data frames, the original effect names are not kept, but replaced by x and group. As ggpredict even takes the variable names as argument, this seems a missed chance to create fully fledged plots right out of the box.

**Comment by strengejacke** [comment]
The intention was, similar to the *broom*-package, to get standardized names in the returned data frame, for general use - no matter, which variable names you have. So, it's intended by design.

But you have all necessary information in the data frame's attributes (see `str(obj)`), and can access the names via the different getters from *ggeffects*.
