### ISSUE TITLE
cannot install from github

### ISSUE THREAD

**Issue by mdwhitby** [strengejacke/ggeffects#51]
devtools::install_github("strengejacke/ggeffects")
Error in read.dcf(path) : 
  Found continuation line starting '    result as tidy d ...' at begin of record.

possibly related to: https://github.com/r-lib/devtools/issues/1900

**Comment by strengejacke** [comment]
I had several issues with devtools, that's why I'm still using the latest 1.x.x version (I think it's 1.3.6). But I'' attach you the source packages here, so you can directly download and install those packages (you need the latest version of _sjstats_ as well, which will be committed by the next 2-3 days, then _ggeffects_ will follow to CRAN).

I would suggest you install ggeffects from CRAN, with `dependencies = TRUE` to install all necessary dependencies, then you can update sjstats and ggeffects from the source.

[sjstats_0.17.2.9000.tar.gz](https://github.com/strengejacke/ggeffects/files/2723381/sjstats_0.17.2.9000.tar.gz)
[ggeffects_0.7.0.9000.tar.gz](https://github.com/strengejacke/ggeffects/files/2723382/ggeffects_0.7.0.9000.tar.gz)

**Comment by mdwhitby** [comment]
Thanks. I'll take that approach. 

I am on devtools 2.0.1 so that is likely the issue. 

Just as an FYI, sjstats installs from github fine with devtools 2.0.1.
