### ISSUE TITLE
synergies/relationships with emmeans, broom.mixed, etc?

### ISSUE THREAD

**Issue by bbolker** [strengejacke/ggeffects#70]
I'm watching you add methods for more and more different model types and wondering whether there is some room for connections with `broom.mixed` ...

**Comment by strengejacke** [comment]
What kind of connections do you have in mind? `augment()` comes to my mind, what comes closest to what `ggpredict()` does.

**Comment by bbolker** [comment]
I'm not sure.  It just occurs to me that there might be a lot of redundant effort in (e.g.) extracting parameters and standard errors from different kinds of models. (In addition to `ggeffects` and `emmeans` we also have `effects` ...)

**Comment by strengejacke** [comment]
But aren't broom.mixed and ggeffects referring to different parameters and standard errors? ggeffects only computes predicted values and their standard errors, _at specific values_. These differ from the coefficients and their standard error as returned by broom(.mixed). 

ggeffects is actually a "wrapper" around `predict()`, `emmeans()` and `effect()`, with all of those functions having a `gg`-prefix (meanwhile, I think this naming style is a bit unlucky, but too late to change...). I decided to also wrap emmans and effects, because 1) they differ to predict in the way they hold factors constant and 2) I wanted a "unique" interface. Actually, you can just replace `ggpredict()` with `ggemmeans()` or `ggeffect()`, without changing the arguments.

The reason why there's another package (beyond emmeans, effects and margins / prediction) is that none of them supported newer mixed models packages like glmmTMB or GLMMadpative (though you have implemented support for effects/emmeans in glmmTMB now), or getting marginal effects for different levels of random effects was not possible etc. (see https://strengejacke.github.io/ggeffects/articles/randomeffects.html#marginal-effects-for-each-level-of-random-effects), and no support for labelled data, but that's more a minor issue.

But getting back to your initial point: I'm just adding "predict()-wrapper" to my package, extracting parameters is mostly done by `predict()`, maybe some reshaping is necessary. For emmeans, I actually don't add support for new models, I just do some reshaping. I'm happy to benefit from synergies with other packages, but yet I'm a bit unsure in which direction to head...

**Comment by bbolker** [comment]
OK, thanks, that's clearer now.  Sorry to bother you.
